Repository cms-data/GeneratorInterface-EvtGenInterface, pull requests merged in 2021-06, with the labels that each got.

#19 added new pdl files for Bs modified lifetime w comments
  evt_Bsmm40.pdl
  evt_Bsmm45.pdl
  evt_Bsmm50.pdl
  evt_Bsmm55.pdl
  evt_Bsmm60.pdl
  evt_Bsmm65.pdl
  evt_Bsmm70.pdl
  evt_Bsmm75.pdl
  evt_Bsmm80.pdl
Labels: externals-approved, fully-signed, generators-approved, orp-pending, tests-approved

#20 Addition of .pdl and .DEC files for MC production of B => mu HNL X
  HNLdecay_mass1.0_maj_emu.DEC
  HNLdecay_mass1.5_maj_emu.DEC
  HNLdecay_mass2.0_maj_emu.DEC
  HNLdecay_mass2.0_maj_emu_Bc.DEC
  HNLdecay_mass3.0_maj_emu.DEC
  HNLdecay_mass3.0_maj_emu_Bc.DEC
  HNLdecay_mass4.5_maj_emu.DEC
  HNLdecay_mass4.5_maj_emu_Bc.DEC
  HNLdecay_mass5.5_maj_emu_Bc.DEC
  evt_BHNL_mass1.0_ctau10.0_maj.pdl
  evt_BHNL_mass1.0_ctau100.0_maj.pdl
  evt_BHNL_mass1.0_ctau1000.0_maj.pdl
  evt_BHNL_mass1.0_ctau10000.0_maj.pdl
  evt_BHNL_mass1.5_ctau10.0_maj.pdl
  evt_BHNL_mass1.5_ctau100.0_maj.pdl
  evt_BHNL_mass1.5_ctau1000.0_maj.pdl
  evt_BHNL_mass1.5_ctau10000.0_maj.pdl
  evt_BHNL_mass2.0_ctau10.0_maj.pdl
  evt_BHNL_mass2.0_ctau100.0_maj.pdl
  evt_BHNL_mass2.0_ctau1000.0_maj.pdl
  evt_BHNL_mass2.0_ctau10000.0_maj.pdl
  evt_BHNL_mass3.0_ctau1.0_maj.pdl
  evt_BHNL_mass3.0_ctau10.0_maj.pdl
  evt_BHNL_mass3.0_ctau100.0_maj.pdl
  evt_BHNL_mass3.0_ctau1000.0_maj.pdl
  evt_BHNL_mass4.5_ctau0.1_maj.pdl
  evt_BHNL_mass4.5_ctau1.0_maj.pdl
  evt_BHNL_mass4.5_ctau10.0_maj.pdl
  evt_BHNL_mass4.5_ctau100.0_maj.pdl
  evt_BHNL_mass5.5_ctau0.01_maj.pdl
  evt_BHNL_mass5.5_ctau0.1_maj.pdl
  evt_BHNL_mass5.5_ctau1.0_maj.pdl
  evt_BHNL_mass5.5_ctau10.0_maj.pdl
Labels: externals-approved, fully-signed, generators-approved, orp-approved, tests-started

#21 Cherry-pick #20 commits over 02-00-11 against 10_2
  HNLdecay_mass1.0_maj_emu.DEC
  HNLdecay_mass1.5_maj_emu.DEC
  HNLdecay_mass2.0_maj_emu.DEC
  HNLdecay_mass2.0_maj_emu_Bc.DEC
  HNLdecay_mass3.0_maj_emu.DEC
  HNLdecay_mass3.0_maj_emu_Bc.DEC
  HNLdecay_mass4.5_maj_emu.DEC
  HNLdecay_mass4.5_maj_emu_Bc.DEC
  HNLdecay_mass5.5_maj_emu_Bc.DEC
  evt_BHNL_mass1.0_ctau10.0_maj.pdl
  evt_BHNL_mass1.0_ctau100.0_maj.pdl
  evt_BHNL_mass1.0_ctau1000.0_maj.pdl
  evt_BHNL_mass1.0_ctau10000.0_maj.pdl
  evt_BHNL_mass1.5_ctau10.0_maj.pdl
  evt_BHNL_mass1.5_ctau100.0_maj.pdl
  evt_BHNL_mass1.5_ctau1000.0_maj.pdl
  evt_BHNL_mass1.5_ctau10000.0_maj.pdl
  evt_BHNL_mass2.0_ctau10.0_maj.pdl
  evt_BHNL_mass2.0_ctau100.0_maj.pdl
  evt_BHNL_mass2.0_ctau1000.0_maj.pdl
  evt_BHNL_mass2.0_ctau10000.0_maj.pdl
  evt_BHNL_mass3.0_ctau1.0_maj.pdl
  evt_BHNL_mass3.0_ctau10.0_maj.pdl
  evt_BHNL_mass3.0_ctau100.0_maj.pdl
  evt_BHNL_mass3.0_ctau1000.0_maj.pdl
  evt_BHNL_mass4.5_ctau0.1_maj.pdl
  evt_BHNL_mass4.5_ctau1.0_maj.pdl
  evt_BHNL_mass4.5_ctau10.0_maj.pdl
  evt_BHNL_mass4.5_ctau100.0_maj.pdl
  evt_BHNL_mass5.5_ctau0.01_maj.pdl
  evt_BHNL_mass5.5_ctau0.1_maj.pdl
  evt_BHNL_mass5.5_ctau1.0_maj.pdl
  evt_BHNL_mass5.5_ctau10.0_maj.pdl
Labels: externals-pending, generators-pending, orp-pending, pending-signatures, tests-pending
